version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 3
  groups:
    ruby-dependencies:
      patterns:
        - "*"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 1
  groups:
    github-actions:
      patterns:
        - "*"
